ALTER TABLE public.firms
ADD COLUMN phone TEXT,
ADD COLUMN email TEXT,
ADD COLUMN website TEXT,
ADD COLUMN address_line1 TEXT,
ADD COLUMN address_line2 TEXT,
ADD COLUMN city TEXT,
ADD COLUMN state TEXT,
ADD COLUMN zip TEXT,
ADD COLUMN bd_number TEXT,
ADD COLUMN crd_number TEXT,
ADD COLUMN notes TEXT,
ADD COLUMN founded_year INTEGER,
ADD COLUMN total_aum NUMERIC DEFAULT 0;